import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href='/static'
            className={styles.card}
          >
            <h2>Static</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </Link>

          <Link href='/server'
            className={styles.card}
          >
            <h2>Server</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </Link>
        </div>
      </main>

    </div>
  )
}
